# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  son-rest-api-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: son-rest-api-mysql
    volumes:
      - son-rest-api-mysql-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=son-rest-api
      - MYSQL_DATABASE=son-rest-api
      - MYSQL_USER=son-rest-api
      - MYSQL_PASSWORD=son-rest-api
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: son-rest-api-app
    depends_on:
      - mysql
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
